name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install Fuel toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://install.fuel.network/fuelup-init.sh | sh
        echo "$HOME/.fuelup/bin" >> $GITHUB_PATH

    - name: Source Fuel environment
      run: |
        source ~/.bashrc || true
        export PATH="$HOME/.fuelup/bin:$PATH"
        echo "PATH=$PATH" >> $GITHUB_ENV

    - name: Install latest Fuel toolchain
      run: |
        fuelup toolchain install latest
        fuelup default latest
        fuelup component add forc fuel-core

    - name: Verify Fuel installation
      run: |
        forc --version
        fuel-core --version

    - name: Install dependencies
      run: bun install

    - name: Build Sway programs and generate TypeScript types
      run: bun run build

    - name: Type check
      run: bun run type-check

    - name: Run tests
      run: bun test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results.xml
          coverage/
        retention-days: 7 